### PR TITLE
New shapes project

### PR DESCRIPTION
**Pull request by vancauwe**
Project shapes and their test shapes.

### CODE REVIEW

**Review by rmfranken — CHANGES_REQUESTED** [review]

**Comment by vancauwe** [comment]
For the `LessThanExampleShape` I am not sure how to link the NodeShape to the property shape of the start date.

**Comment by vancauwe** [comment]
for `schema:Project-domain` I have right now that the path is towards `ex:Domain` but also that the constraint is that it is a `sh:class ex:Domain`... I feel like I am confusing notions

**Comment by vancauwe** [comment]
what is `ex:` referring to ? (for `ex:Domain`), I cannot find the URL to the ontology anywhere (or does it mean `example`?)

**Comment by vancauwe** [comment]
2 design questions: 
- `Project-code`: restrict to GitHub and Gitlab with a regex? 
- would it make sense to have a PropertyShape technical specifications for the project which would encompass programming language, but also other aspects like Server, infrastructure, and other tools?

**Comment by rmfranken** [comment]
> For the `LessThanExampleShape` I am not sure how to link the NodeShape to the property shape of the start date.

A lessThan is a constraint component between two nodes. You can say for example in the startDate propertyShape:

`schema:Project-startDate
  a sh:PropertyShape ;
  sh:path schema:startDate ;
  sh:description "The date on which the project started."^^rdf:HTML ;
  sh:name "projectStartDate" ;
  sh:lessThanOrEquals schema:endDate ;
  sh:or (
      [
        sh:datatype xsd:date ;
      ]
      [
        sh:datatype xsd:string ;
      ]
    ) ;
.`

So you are saying that whatever value is found as the "object" in the triple { <subject> schema:startDate "value" } must be less than the value found for {<subject> schema:endDate "value" }. You don't need to create a seperate lessThan nodeshape.

**Comment by rmfranken** [comment]
> for `schema:Project-domain` I have right now that the path is towards `ex:Domain` but also that the constraint is that it is a `sh:class ex:Domain`... I feel like I am confusing notions

your feeling is grounded in truth. The reason is probably because there exists no "domain" property in the graph right now. 

We have schema:knowsAbout, which also has as it's sh:class a ex:Domain, but we don't have a "domain". 

You could define a property hasDomain maybe, which loosely relates one project to 1 or more domains, and by domains we mean ex:Domain's. ahaha.

**Comment by rmfranken** [comment]
> what is `ex:` referring to ? (for `ex:Domain`), I cannot find the URL to the ontology anywhere (or does it mean `example`?)

right now, ex: is just a prefix to placehold until we decide on a prefix we want to use for our own ontology. it generally stands for  <http://example.org/>

**Comment by rmfranken** [comment]
> 2 design questions:
> 
>     * `Project-code`: restrict to GitHub and Gitlab with a regex?
> 
>     * would it make sense to have a PropertyShape technical specifications for the project which would encompass programming language, but also other aspects like Server, infrastructure, and other tools?

Yes, that would make sense if we expect our users to only use those two repositories for their codebases, which I think is a fair assumption.

Yes, it's a good idea, but I think we should put that on a backlog. The world of code infrastructure is a scattered one with many conflicting definitions, and we have to ask ourselves the questions that people want to answer by having that information. I think this is something that might be useful, but takes a lot of time to model nicely. So for now, I would keep my fingers away from formally modelling it.

**Comment by rmfranken** [comment]
line 247 sh:class schema:computerLanguage ;
  
  this should be schema:ComputerLanguage as it is an object (so camelcased instead of pascald)

**Comment by rmfranken** [comment]
:isConfidential
  a rdfs:Class ;
  a sh:NodeShape ;
  rdfs:comment "Confidentiality information. "^^rdf:HTML ;
  rdfs:label "ConfidentialityInformation" ;
.

This is close, but it is not a class or nodeshape. Just an rdf:Property. I would make it like this:

 :isConfidential a rdf:Property ;
   rdfs:comment "A property defining whether something is confidential or not. Confidentiality indicates that whatever object this is applied to may not be openly shared with the public. "^^rdf:HTML ;
  rdfs:label "Confidentiality Information" ;
.

**Comment by rmfranken** [comment]
schema:Project-code
  a sh:PropertyShape ;
  sh:path schema:codeRepository ;
  sh:description "The open source code tied to the project. A URL to a repository. "^^rdf:HTML ;
  sh:name "projectCode" ;
  sh:datatype xsd:url ;
.

I think we could also rename the propertyshape here to schema:Project-codeRepository, and change the sh:name similarly.

**Comment by vancauwe** [comment]
Update on latest tests: 
- Domain properties commented out to avoid SHACL error about undefined `ex:` domain
- Person `minCount` and `maxCount` properties commented out to facilitate testing 
- added a `fte` property because PropertyShape `Project-FTE` was without a path

Worrying bug: 
on my last docker run for testing, I got a disconnect error from schema.org that I cannot explain. 

Almost good to go but would need a last look over @rmfranken !

**Pull request merged**
